### ISSUE TITLE
Crash in SDK

### ISSUE THREAD

**Issue by DanilKuhta** [socure-inc/socure-sigmadevice-sdk-android#12]
When using SDK in the project, where we have google.android.play-services-location version 21.0.1,
it crashes with an exception:
`java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient')
                                                                                                    	at com.socure.idplus.devicerisk.androidsdk.sensors.SocureSigmaDevice.checkLocation(SocureSigmaDevice.kt:102)
                                                                                                    	at com.socure.idplus.devicerisk.androidsdk.sensors.SocureSigmaDevice.fingerPrint(SocureSigmaDevice.kt:81)`

Not the case when using 20.0.0

**Comment by buraksocure** [comment]
Thanks for reporting this @DanilKuhta We will review and get back to you.

**Comment by buraksocure** [comment]
Hi @DanilKuhta This issue will be taken care of on upcoming release. I'll let you know once I have an ETA.

**Comment by buraksocure** [comment]
Hi @DanilKuhta We released new version of our SDK (https://github.com/socure-inc/socure-sigmadevice-sdk-android/releases/tag/2.0.2) and update location services library to "com.google.android.gms:play-services-location:21.0.1" Please try and let us know if it resolves your issue.
