### ISSUE TITLE
SDK Crashes on API 23-25

### ISSUE THREAD

**Issue by jt-gilkeson** [socure-inc/socure-sigmadevice-sdk-android#18]
We updated our Socure SDKs to the latest because of the Jitpack hosting problems with the older Socure SDKs that we were using.  
We've tried both 4.1.0 and 4.1.1 We see the following crashes on Phones with `SDK 23-25`.  These are debug builds (no proguard/r8)  Your SDK indicates: `Min SDK 21`
(Happens in Nexus 5/5x emulator in android studio as well as devices on Firebase): 

If the app already has location permission (update app scenario):

```
 java.lang.NoSuchMethodError: No virtual method getVerticalAccuracyMeters()F in class Landroid/location/Location; or its super classes (declaration of 'android.location.Location' appears in /system/framework/framework.jar)
  	at com.socure.idplus.device.internal.viewModel.deviceV2.a.a(SourceFile)
       	at com.socure.idplus.device.internal.g.invoke(SourceFile:4)
     	at com.socure.idplus.device.internal.sigmaDeviceLocation.manager.a.invoke(SourceFile:1)
      	at com.socure.idplus.device.internal.viewModel.location.a.invoke(SourceFile:1)
    	at com.socure.idplus.device.internal.viewModel.location.b.a(SourceFile:2)
     	at com.socure.idplus.device.internal.viewModel.location.b$$ExternalSyntheticLambda0.onSuccess(D8$$SyntheticClass:0)
    	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
  	at android.os.Handler.handleCallback(Handler.java:739)
   	at android.os.Handler.dispatchMessage(Handler.java:95)
  	at android.os.Looper.loop(Looper.java:148)
   	at android.app.ActivityThread.main(ActivityThread.java:5417)
   	at java.lang.reflect.Method.invoke(Native Method)
   	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

No location permission yet (new install):
```
java.lang.NoSuchMethodError: No virtual method getCalendarType()Ljava/lang/String; in class Ljava/util/Calendar; or its super classes (declaration of 'java.util.Calendar' appears in /system/framework/core-oj.jar)
	at com.socure.idplus.device.internal.utils.e$$ExternalSyntheticApiModelOutline0.m(SourceFile:0)
	at com.socure.idplus.device.internal.utils.e.a(SourceFile:2)
	at com.socure.idplus.device.internal.viewModel.deviceV2.a.a(SourceFile:5)
	at com.socure.idplus.device.internal.g.invoke(SourceFile:4)
	at com.socure.idplus.device.internal.sigmaDeviceLocation.manager.a.invoke(SourceFile:1)
	at com.socure.idplus.device.internal.sigmaDeviceLocation.manager.f.a(SourceFile:5)
	at com.socure.idplus.device.internal.sigmaDeviceLocation.manager.f$$ExternalSyntheticLambda0.onSuccess(SourceFile:0)
	at com.google.android.gms.tasks.zzm.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by jt-gilkeson** [comment]
4.0.1 doesn't seem to have the calendar issue but does have a location issue:
```
java.lang.NoSuchMethodError: No virtual method getVerticalAccuracyMeters()F in class Landroid/location/Location; or its super classes (declaration of 'android.location.Location' appears in /system/framework/framework.jar)
 	at com.socure.idplus.device.internal.sigmaDeviceLocation.manager.d.a(SourceFile:13)
   	at com.socure.idplus.device.internal.sigmaDeviceLocation.manager.a.invokeSuspend(SourceFile)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
   	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
  	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
   	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
     	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
```

**Comment by rburunkayaSocure** [comment]
Hi @jt-gilkeson 

Thanks for contacting us. We are planning to release a fix tomorrow for addressing the issues. We are going to notify you when the fix in place.

Thanks,

**Comment by rburunkayaSocure** [comment]
Hi @jt-gilkeson 

We released new version of our SDK(https://github.com/socure-inc/socure-sigmadevice-sdk-android/releases/tag/4.1.2). Please let us know if you have any further questions.

Kind regards,

**Comment by jt-gilkeson** [comment]
@rburunkayaSocure   Thank you for the quick fix.  I can confirm that the two crashes no longer happen.
